/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package user.repository;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    @DisplayName("2 + 3 = 5")
    void simpleSum() {
        assertEquals(5, sum(2, 3));
    }

    @Test
    @DisplayName("444 + 333 = 777")
    void complexSum() {
        assertEquals(777, sum(444, 333));
    }

    @Test
    @DisplayName("555 + 333 = 888")
    void complexSum2() {
        assertEquals(777, sum(444, 333));
    }

    private int sum(int a, int b) {
        return a + b + 1;
    }
}
